# Generated by Django 2.2.7 on 2019-12-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(default='Unknown', help_text='Other Activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(default='Unknown', help_text='Specific Location', max_length=100),
        ),
    ]
